[versions]
armorStatuesCompanion = "1.4.1"
fabric-loom = "1.14.0-alpha.9"
kotlin-jvm = "2.0.21"
modrinth-minotaur = "2.+"
curseGradle= "1.6.1"
minecraft = "1.21.10"
yarn-mappings = "1.21.10+build.3"
fabric-loader = "0.18.1"
fabric-api = "0.138.3+1.21.10"
fabric-kotlin = "1.11.0+kotlin.2.0.0"
owo = "0.12.24+1.21.9"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
owo-lib = { module = "io.wispforest:owo-lib", version.ref = "owo" }
owo-sentinel = { module = "io.wispforest:owo-sentinel", version.ref = "owo" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
modrinth-minotaur = { id = "com.modrinth.minotaur", version.ref = "modrinth-minotaur" }
curseGradle = { id = "io.github.CDAGaming.cursegradle", version.ref = "curseGradle" }
